apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
spec:
  selector:
    app: debezium-connect
  ports:
    - port: 8083
      targetPort: 8083
      name: connect-api
  type: ClusterIP 