apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  type: ClusterIP 