apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-internal
    - port: 9093
      targetPort: 9093
      name: kafka-external
  type: ClusterIP 