apiVersion: v1
kind: ServiceAccount
metadata:
  name: saga-demo-sa
  namespace: saga-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: saga-demo-role
  namespace: saga-demo
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: saga-demo-role-binding
  namespace: saga-demo
subjects:
- kind: ServiceAccount
  name: saga-demo-sa
  namespace: saga-demo
roleRef:
  kind: Role
  name: saga-demo-role
  apiGroup: rbac.authorization.k8s.io 