apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  type: ClusterIP 