apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  labels:
    app: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: order-db-data
              mountPath: /var/lib/postgresql/data
            - name: order-db-init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-pvc
        - name: order-db-init
          configMap:
            name: order-db-init 