apiVersion: v1
kind: Service
metadata:
  name: order-db
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP 